package com.aaroncoplan.waterfall.compiler.tests

import com.aaroncoplan.waterfall.compiler.ir.IrLowering
import com.aaroncoplan.waterfall.compiler.statements.ModuleAst
import com.aaroncoplan.waterfall.compiler.symboltables.SymbolTable
import com.aaroncoplan.waterfall.compiler.verifier.HumanRenderer
import com.aaroncoplan.waterfall.compiler.verifier.Verifier
import com.aaroncoplan.waterfall.parser.FileParser
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.Parameterized
import java.nio.file.Files
import javax.json.Json
import javax.json.JsonObject

/**
 * Adversarial regression suite for Sub-task 4.1 (UnknownIdentifier + OQ-11.6=strict).
 * Fixture: compiler/src/test/resources/adversarial/phase-11/sub-task-4.1/programs.json
 *
 * **Two outcome categories** (§4.1 only; no `lower_fail` entries):
 * - `compile_success` — program verifies AND lowers to IR without throwing.
 * - `verify_fail:<substr>` — verifier rejects; [HumanRenderer] output contains substr.
 *
 * **No `lower_fail` category**: Under OQ-11.3=(a), all undeclared identifiers are caught
 * at verify time by [Elaboration] or [StatementVerifier]. No undeclared-identifier program
 * reaches [IrLowering] in §4.1 state. The P10 `lower_fail` category (cast-to-unknown-type)
 * is absent from §4.1 because cast-target validation lands in §4.2.
 *
 * **Fixture authorship (R8 prompt-context independence):**
 * The stub fixture (2 entries) was written by the tester alongside this runner.
 * The full 24-entry fixture is generated by a fresh-context Agent reading the §4.1
 * commit diff AFTER commit 2 lands, per playbook §3 Leg 3. The runner loads whatever
 * JSON is present; the fixture file is replaced in commit 3.
 *
 * **Pattern mirrors** [Sub54AdversarialTest] from phase-10/sub-task-5.4.
 */
@RunWith(Parameterized::class)
class Sub41AdversarialTest(private val entry: Sub41Entry) {

    data class Sub41Entry(
        val name: String,
        val source: String,
        val expectedOutcome: String,   // "compile_success" or "verify_fail:<substr>"
        val rationale: String
    )

    @Test fun `program outcome matches prediction`() {
        val tmp = Files.createTempFile("sub41-${entry.name}-", ".wf")
        try {
            Files.write(tmp, entry.source.toByteArray())
            val filePath = tmp.toString()
            val parseResult = FileParser.parseCodeString(filePath, entry.source)
            // Syntax errors: treat as verification failure
            if (parseResult.hasErrors()) {
                val syntaxErrors = parseResult.getSyntaxErrors().joinToString("; ")
                when {
                    entry.expectedOutcome.startsWith("verify_fail:") -> {
                        val substr = entry.expectedOutcome.removePrefix("verify_fail:")
                        assertTrue(
                            "Expected verify_fail substring '$substr' but got syntax errors: $syntaxErrors",
                            syntaxErrors.contains(substr)
                        )
                    }
                    entry.expectedOutcome == "compile_success" -> fail(
                        "Positive program [${entry.name}] has syntax errors: $syntaxErrors\n" +
                        "Rationale: ${entry.rationale}"
                    )
                    else -> { /* unexpected outcome category — fall through to else branch below */ }
                }
                return
            }

            val moduleAst = ModuleAst(filePath, parseResult.getProgramAST().module())
            val symbolTable = SymbolTable()
            val verifyResult = Verifier.verifyModule(moduleAst, symbolTable)

            when {
                entry.expectedOutcome == "compile_success" -> {
                    assertTrue(
                        "Positive program [${entry.name}] should verify but got errors:\n" +
                        verifyResult.errors.joinToString("\n") { HumanRenderer.render(it) } +
                        "\nRationale: ${entry.rationale}",
                        verifyResult.isSuccessful
                    )
                    // Also lower — compile_success means lowering must not throw
                    IrLowering.lowerModule(moduleAst, verifyResult.resolvedTypes)
                }

                entry.expectedOutcome.startsWith("verify_fail:") -> {
                    val substr = entry.expectedOutcome.removePrefix("verify_fail:")
                    assertFalse(
                        "Expected verify failure for [${entry.name}] but verifier passed.\nRationale: ${entry.rationale}",
                        verifyResult.isSuccessful
                    )
                    val rendered = verifyResult.errors.joinToString("\n") { HumanRenderer.render(it) }
                    assertTrue(
                        "Program [${entry.name}]: expected verify error substring '$substr' but got:\n$rendered",
                        rendered.contains(substr)
                    )
                }

                else -> fail("Unknown expectedOutcome for [${entry.name}]: '${entry.expectedOutcome}'. " +
                        "§4.1 outcome categories are 'compile_success' and 'verify_fail:<substr>' only.")
            }
        } finally {
            Files.deleteIfExists(tmp)
        }
    }

    companion object {
        @JvmStatic
        @Parameterized.Parameters(name = "{0}")
        fun load(): List<Array<Any>> {
            val stream = Sub41AdversarialTest::class.java
                .getResourceAsStream("/adversarial/phase-11/sub-task-4.1/programs.json")
                ?: error("Fixture not found at compiler/src/test/resources/adversarial/phase-11/sub-task-4.1/programs.json")
            return stream.use { s ->
                val root = Json.createReader(s).readObject()
                val positives = root.getJsonArray("positive_entries").map { it as JsonObject }
                val negatives = root.getJsonArray("negative_entries").map { it as JsonObject }
                (positives + negatives).map { e ->
                    arrayOf(Sub41Entry(
                        name = e.getString("name"),
                        source = e.getString("source"),
                        expectedOutcome = e.getString("expected_outcome"),
                        rationale = e.getString("rationale")
                    ) as Any)
                }
            }
        }
    }
}
