package com.aaroncoplan.waterfall.compiler.tests

import com.aaroncoplan.waterfall.compiler.ir.IrLowering
import com.aaroncoplan.waterfall.compiler.statements.ModuleAst
import com.aaroncoplan.waterfall.compiler.symboltables.SymbolTable
import com.aaroncoplan.waterfall.compiler.verifier.HumanRenderer
import com.aaroncoplan.waterfall.compiler.verifier.Verifier
import com.aaroncoplan.waterfall.parser.FileParser
import org.junit.Assert.*
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.Parameterized
import java.nio.file.Files
import javax.json.Json
import javax.json.JsonObject

/**
 * Adversarial regression suite for Sub-task 5.4 (IR + IrLowering).
 * Fixture: compiler/src/test/resources/adversarial/phase-10/sub-task-5.4/programs.json
 * Generated by a fresh-context Agent reading §3 + §5.4 (Leg 3, R8 prompt-context
 * independence). 77 total entries across 3 outcome categories.
 *
 * **Three outcome categories (new in §5.4 vs. §5.2/§5.3):**
 * - `compile_success` — program verifies AND lowers to IR without throwing.
 * - `verify_fail:<substr>` — verifier rejects; HumanRenderer output contains substr.
 * - `lower_fail:<substr>` — verifier passes; IrLowering throws with substr in message.
 *
 * **OQ-5.4-1 (Leg 3 catch):** `lower_fail` entries test IrType.fromWaterfallType
 * throwing on ErrorType inputs (e.g., cast to unknown type). Undeclared-identifier
 * programs are compile_success (not lower_fail) because Elaboration stores VoidType
 * for undeclared names; IrLowering produces Identifier(name, IrType.Void) without
 * throwing — the OQ-5.4-1 resolved behavior.
 */
@RunWith(Parameterized::class)
class Sub54AdversarialTest(private val entry: Sub54Entry) {

    data class Sub54Entry(
        val name: String,
        val source: String,
        val expectedOutcome: String,  // "compile_success", "verify_fail:<substr>", "lower_fail:<substr>"
        val rationale: String
    )

    @Test fun `program outcome matches prediction`() {
        val tmp = Files.createTempFile("sub54-${entry.name}-", ".wf")
        try {
            Files.write(tmp, entry.source.toByteArray())
            val filePath = tmp.toString()
            val parseResult = FileParser.parseCodeString(filePath, entry.source)
            // Some adversarial programs may have syntax errors — check before proceeding
            if (parseResult.hasErrors()) {
                // Treat as a verify failure: syntax errors are caught upstream
                val syntaxErrors = parseResult.getSyntaxErrors().joinToString("; ")
                when {
                    entry.expectedOutcome.startsWith("verify_fail:") -> {
                        val substr = entry.expectedOutcome.removePrefix("verify_fail:")
                        assertTrue(
                            "Expected verify_fail substring '$substr' but got syntax errors: $syntaxErrors",
                            syntaxErrors.contains(substr)
                        )
                    }
                    entry.expectedOutcome == "compile_success" -> fail(
                        "Positive program [${entry.name}] has syntax errors: $syntaxErrors\n" +
                        "Rationale: ${entry.rationale}"
                    )
                    else -> { /* lower_fail programs that have syntax errors — unusual but accept */ }
                }
                return
            }

            val moduleAst = ModuleAst(filePath, parseResult.getProgramAST().module())
            val symbolTable = SymbolTable()
            val verifyResult = Verifier.verifyModule(moduleAst, symbolTable)

            when {
                entry.expectedOutcome == "compile_success" -> {
                    assertTrue(
                        "Positive program [${entry.name}] should verify but got errors:\n" +
                        verifyResult.errors.joinToString("\n") { HumanRenderer.render(it) } +
                        "\nRationale: ${entry.rationale}",
                        verifyResult.isSuccessful
                    )
                    // Also lower — compile_success means lowering must not throw
                    IrLowering.lowerModule(moduleAst, verifyResult.resolvedTypes)
                }

                entry.expectedOutcome.startsWith("verify_fail:") -> {
                    val substr = entry.expectedOutcome.removePrefix("verify_fail:")
                    assertFalse(
                        "Expected verify failure for [${entry.name}] but verifier passed.\nRationale: ${entry.rationale}",
                        verifyResult.isSuccessful
                    )
                    val rendered = verifyResult.errors.joinToString("\n") { HumanRenderer.render(it) }
                    assertTrue(
                        "Program [${entry.name}]: expected verify error substring '$substr' but got:\n$rendered",
                        rendered.contains(substr)
                    )
                }

                entry.expectedOutcome.startsWith("lower_fail:") -> {
                    val substr = entry.expectedOutcome.removePrefix("lower_fail:")
                    assertTrue(
                        "Program [${entry.name}] (lower_fail) must verify first but got errors:\n" +
                        verifyResult.errors.joinToString("\n") { HumanRenderer.render(it) },
                        verifyResult.isSuccessful
                    )
                    try {
                        IrLowering.lowerModule(moduleAst, verifyResult.resolvedTypes)
                        fail("Program [${entry.name}]: expected IrLowering to throw IllegalStateException\nRationale: ${entry.rationale}")
                    } catch (e: IllegalStateException) {
                        val msg = e.message ?: ""
                        assertTrue(
                            "Program [${entry.name}]: expected exception substring '$substr' but got: $msg",
                            msg.contains(substr)
                        )
                    }
                }

                else -> fail("Unknown expectedOutcome for [${entry.name}]: '${entry.expectedOutcome}'")
            }
        } finally {
            Files.deleteIfExists(tmp)
        }
    }

    companion object {
        @JvmStatic
        @Parameterized.Parameters(name = "{0}")
        fun load(): List<Array<Any>> {
            val stream = Sub54AdversarialTest::class.java
                .getResourceAsStream("/adversarial/phase-10/sub-task-5.4/programs.json")
                ?: error("Fixture not found at compiler/src/test/resources/adversarial/phase-10/sub-task-5.4/programs.json")
            return stream.use { s ->
                val root = Json.createReader(s).readObject()
                val positives = root.getJsonArray("positive_entries").map { it as JsonObject }
                val negatives = root.getJsonArray("negative_entries").map { it as JsonObject }
                (positives + negatives).map { e ->
                    arrayOf(Sub54Entry(
                        name = e.getString("name"),
                        source = e.getString("source"),
                        expectedOutcome = e.getString("expected_outcome"),
                        rationale = e.getString("rationale")
                    ) as Any)
                }
            }
        }
    }
}
