package com.aaroncoplan.waterfall.compiler.tests

import com.aaroncoplan.waterfall.compiler.CompilerError
import com.aaroncoplan.waterfall.compiler.Main
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.Parameterized
import java.io.ByteArrayOutputStream
import java.io.PrintStream
import java.nio.file.Files
import javax.json.Json
import javax.json.JsonObject

/**
 * Adversarial regression suite for Sub-task 5.3 (Verifier package + verify() migration).
 * Fixture: compiler/src/test/resources/adversarial/phase-10/sub-task-5.3/programs.json
 * Generated by a fresh-context Agent reading §4 + §5.3 (Leg 3, R8 prompt-context
 * independence). 25 positive + 35 negative = 60 programs.
 *
 * Bug caught by this Agent: neg-21 through neg-24 revealed that VoidNotAValueType was
 * defined but never emitted — `void x = 5` compiled cleanly instead of being rejected.
 * Fixed in commit 5.5 before this fixture landed. This is the verification triad
 * working as designed (Leg 3 surfacing a compiler-broke outcome per playbook §5).
 *
 * Outcomes:
 *   PASSED         — positive compiles cleanly OR negative fails with expected substring
 *   compiler-broke — positive throws CompilerError (impl bug)
 *   false-rejected — positive throws but spec says valid (escalate)
 *   wrong-error    — negative fails but stderr substring doesn't match prediction
 */
@RunWith(Parameterized::class)
class Sub53AdversarialTest(private val entry: Sub53Entry) {

    data class Sub53Entry(
        val name: String,
        val source: String,
        val category: String,            // "positive" or "negative"
        val expectedErrorSubstring: String?,  // required for negative; null for positive
        val rationale: String
    )

    private lateinit var originalOut: PrintStream
    private lateinit var originalErr: PrintStream
    private lateinit var capturedErr: ByteArrayOutputStream

    @Before fun redirectStreams() {
        originalOut = System.out
        originalErr = System.err
        capturedErr = ByteArrayOutputStream()
        System.setOut(PrintStream(ByteArrayOutputStream()))
        System.setErr(PrintStream(capturedErr))
    }

    @After fun restoreStreams() {
        System.setOut(originalOut)
        System.setErr(originalErr)
    }

    @Test fun `program compiles or fails as predicted`() {
        val tmp = Files.createTempFile("waterfall-sub53-${entry.name}-", ".wf")
        try {
            Files.write(tmp, entry.source.toByteArray())
            var thrown: CompilerError? = null
            try {
                Main.run(arrayOf(tmp.toString()))
            } catch (e: CompilerError) {
                thrown = e
            }
            val stderr = capturedErr.toString()
            when (entry.category) {
                "positive" -> {
                    assertNull(
                        "Positive program [${entry.name}] should compile but threw " +
                        "CompilerError: ${thrown?.message}\nstderr:\n$stderr\nRationale: ${entry.rationale}",
                        thrown
                    )
                }
                "negative" -> {
                    assertNotNull(
                        "Negative program [${entry.name}] should fail but compiled cleanly. " +
                        "Rationale: ${entry.rationale}",
                        thrown
                    )
                    val expected = entry.expectedErrorSubstring
                        ?: error("Negative entry [${entry.name}] missing expected_error_substring")
                    assertTrue(
                        "Negative program [${entry.name}] failed with wrong error. " +
                        "Expected substring: \"$expected\"\nstderr was:\n$stderr",
                        stderr.contains(expected)
                    )
                }
                else -> fail("Unknown category for entry [${entry.name}]: ${entry.category}")
            }
        } finally {
            Files.deleteIfExists(tmp)
        }
    }

    companion object {
        @JvmStatic
        @Parameterized.Parameters(name = "{0}")
        fun load(): List<Array<Any>> {
            val stream = Sub53AdversarialTest::class.java
                .getResourceAsStream("/adversarial/phase-10/sub-task-5.3/programs.json")
                ?: error(
                    "Fixture not found at " +
                    "compiler/src/test/resources/adversarial/phase-10/sub-task-5.3/programs.json"
                )
            return stream.use { s ->
                val root = Json.createReader(s).readObject()
                val positives = root.getJsonArray("positive_entries").map { it as JsonObject }
                val negatives = root.getJsonArray("negative_entries").map { it as JsonObject }
                (positives + negatives).map { e ->
                    arrayOf(Sub53Entry(
                        name = e.getString("name"),
                        source = e.getString("source"),
                        category = e.getString("category"),
                        expectedErrorSubstring = e.getString("expected_error_substring", null),
                        rationale = e.getString("rationale")
                    ) as Any)
                }
            }
        }
    }
}
