package com.aaroncoplan.waterfall.compiler.typesystem

import org.junit.Assert.*
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.Parameterized
import javax.json.Json
import javax.json.JsonObject

/**
 * Adversarial regression suite for WaterfallType.fromSourceText.
 * Fixture: compiler/src/test/resources/adversarial/phase-10/sub-task-5.1/fromSourceText.json
 *
 * Entries generated by a fresh-context Agent reading §1.2 only (Leg 3,
 * R8 prompt-context independence). No external JSON library required —
 * javax.json:1.0.4 is already on the test classpath via ANTLR4's transitive
 * dependency chain.
 *
 * Outcome categories per entry:
 *   PASSED        — prediction matches implementation → good
 *   false-rejected — Agent predicted ErrorType; spec says valid; impl agrees with spec
 *                    → spec-ambiguity finding; escalate to team-lead
 *   compiler-broke — Agent predicted valid type; impl produced wrong type or threw
 *                    → impl bug; route to engineer
 */
@RunWith(Parameterized::class)
class FromSourceTextAdversarialTest(private val entry: AdversarialEntry) {

    data class AdversarialEntry(
        val input: String,
        val expectedClass: String,
        val expectedElementClass: String?,
        val expectedSourceText: String?,
        val category: String,
        val rationale: String
    )

    @Test fun `fromSourceText matches adversarial prediction`() {
        val result = WaterfallType.fromSourceText(entry.input)
        val actualClass = result::class.simpleName

        assertEquals(
            "Input=${repr(entry.input)} [${entry.category}]: " +
            "expected ${entry.expectedClass} but got $actualClass. ${entry.rationale}",
            entry.expectedClass,
            actualClass
        )

        when (result) {
            is WaterfallType.ErrorType -> {
                assertNotNull(
                    "expected_source_text required for ErrorType (input=${repr(entry.input)})",
                    entry.expectedSourceText
                )
                assertEquals(
                    "ErrorType.sourceText mismatch for input=${repr(entry.input)}",
                    entry.expectedSourceText,
                    result.sourceText
                )
            }
            is WaterfallType.ArrayType -> {
                assertNotNull(
                    "expected_element_class required for ArrayType (input=${repr(entry.input)})",
                    entry.expectedElementClass
                )
                assertEquals(
                    "ArrayType.element class mismatch for input=${repr(entry.input)}",
                    entry.expectedElementClass,
                    result.element::class.simpleName
                )
            }
            else -> { /* scalar types: class name check above is sufficient */ }
        }
    }

    companion object {
        /** Produce a debug-friendly representation of the input string, showing escape sequences. */
        private fun repr(s: String): String = buildString {
            append('"')
            for (c in s) {
                when (c) {
                    '\t' -> append("\\t")
                    '\n' -> append("\\n")
                    '\r' -> append("\\r")
                    '"'  -> append("\\\"")
                    else -> if (c.code < 32 || c.code > 126) append("\\u%04X".format(c.code)) else append(c)
                }
            }
            append('"')
        }

        @JvmStatic
        @Parameterized.Parameters(name = "fromSourceText({0})")
        fun load(): List<AdversarialEntry> {
            val stream = FromSourceTextAdversarialTest::class.java
                .getResourceAsStream(
                    "/adversarial/phase-10/sub-task-5.1/fromSourceText.json"
                ) ?: error(
                    "Adversarial fixture not found — expected at " +
                    "compiler/src/test/resources/adversarial/phase-10/sub-task-5.1/fromSourceText.json"
                )
            return stream.use { s ->
                Json.createReader(s).readObject()
                    .getJsonArray("entries")
                    .map { it as JsonObject }
                    .map { e ->
                        AdversarialEntry(
                            input                = e.getString("input"),
                            expectedClass        = e.getString("expected_class"),
                            expectedElementClass = e.getString("expected_element_class", null),
                            expectedSourceText   = e.getString("expected_source_text", null),
                            category             = e.getString("category"),
                            rationale            = e.getString("rationale")
                        )
                    }
            }
        }
    }
}
