package com.aaroncoplan.waterfall.compiler.verifier

import com.aaroncoplan.waterfall.compiler.statements.ModuleAst
import com.aaroncoplan.waterfall.compiler.symboltables.SymbolTable
import com.aaroncoplan.waterfall.parser.FileParser
import io.kotest.property.Arb
import io.kotest.property.arbitrary.of
import io.kotest.property.checkAll
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Property-based tests for [VerifyError.UnknownIdentifier] at N=10,000.
 * Covers §4.1 emission sites + Elaboration expression-context emission (OQ-11.3=(a)).
 *
 * **Style:** JUnit-4-annotated (`@Test`) + Kotest `checkAll` inside `runBlocking`.
 * NOT StringSpec / BehaviorSpec — project runner is JUnit 4 (`useJUnit()` in build.gradle).
 * Pattern mirrors [com.aaroncoplan.waterfall.compiler.symboltables.SymbolTablePropertyTest].
 *
 * **TRIP-WIRE:** after this file lands, run
 *   ./gradlew test --tests UnknownIdentifierPropertyTest
 * If it reports zero tests, the runner integration is broken — escalate before proceeding.
 *
 * **Identifier Arb strategy:**
 * - Declared names use prefix "v" + positive int (e.g. "v42"): valid identifiers, no keyword risk.
 * - Undeclared names use prefix "u" + positive int (e.g. "u99"): guaranteed not declared in the
 *   generated program (which only declares "v"-prefixed names).
 * - This prefix separation avoids accidental collisions and eliminates filtering overhead.
 *
 * **Property 2 — 6 error forms** (statement-level × 4 + expression-context × 2):
 * Under OQ-11.3=(a), Elaboration emits UnknownIdentifier for expression-context IDENTIFIERs.
 * All 6 forms are included to verify completeness across both [StatementVerifier] and
 * [Elaboration] emission paths.
 */
class UnknownIdentifierPropertyTest {

    // ------------------------------------------------------------------ //
    // Arb definitions
    // ------------------------------------------------------------------ //

    /**
     * Valid declared-name generator: "v1".."v9999".
     * Starts with a letter, alphanumeric, no keyword risk.
     * Uses Arb.of with pre-built list (consistent with SymbolTablePropertyTest pattern).
     */
    private val arbDeclaredName: Arb<String> = Arb.of((1..9999).map { "v$it" })

    /**
     * Valid undeclared-name generator: "u1".."u9999".
     * Same shape; guaranteed not present in programs generated by [arbDeclaredName].
     */
    private val arbUndeclaredName: Arb<String> = Arb.of((1..9999).map { "u$it" })

    /** The 6 syntactic positions where UnknownIdentifier can be emitted in §4.1. */
    private enum class ErrorForm {
        ASSIGNMENT_LHS,       // StatementVerifier.verifyVarAssignment
        INCREMENT_TARGET,     // StatementVerifier.verifyIncrement
        FOR_COLLECTION,       // StatementVerifier.verifyForBlock (OQ-11.6=strict)
        LOCAL_CALL,           // StatementVerifier.verifyFunctionCallStatement (OQ-11.6=strict)
        EXPRESSION_RHS,       // Elaboration.elaborateExpression IDENTIFIER (OQ-11.3=(a))
        EXPRESSION_CONDITION, // Elaboration.elaborateExpression IDENTIFIER (OQ-11.3=(a))
    }

    private val arbErrorForm: Arb<ErrorForm> = Arb.of(ErrorForm.entries)

    // ------------------------------------------------------------------ //
    // Source-building helpers
    // ------------------------------------------------------------------ //

    private fun parseAndAst(source: String): ModuleAst {
        val parseResult = FileParser.parseCodeString("prop.wf", source)
        return ModuleAst("prop.wf", parseResult.getProgramAST().module())
    }

    /**
     * Build a minimal module source where [name] is used in the given [form]
     * without being declared anywhere in the module.
     */
    private fun buildUndeclaredSource(form: ErrorForm, name: String): String = when (form) {
        ErrorForm.ASSIGNMENT_LHS ->
            "module M {\n    func f() {\n        $name = 5\n    }\n}"
        ErrorForm.INCREMENT_TARGET ->
            "module M {\n    func f() {\n        $name++\n    }\n}"
        ErrorForm.FOR_COLLECTION ->
            "module M {\n    func f() {\n        for(item in $name) {}\n    }\n}"
        ErrorForm.LOCAL_CALL ->
            "module M {\n    func f() {\n        $name()\n    }\n}"
        ErrorForm.EXPRESSION_RHS ->
            "module M {\n    func f() {\n        int x = $name\n    }\n}"
        ErrorForm.EXPRESSION_CONDITION ->
            "module M {\n    func f() {\n        if($name) {\n            return\n        }\n    }\n}"
    }

    // ------------------------------------------------------------------ //
    // Property 1 — Soundness: declared identifiers produce no UnknownIdentifier
    // ------------------------------------------------------------------ //

    /**
     * **Soundness invariant**: for any program where every identifier reference has
     * been declared in scope, no [VerifyError.UnknownIdentifier] error is emitted.
     *
     * Generator: module with a typed var decl + assignment using the same Arb name.
     * Both the decl and the use are generated together so the name is always in scope
     * at the point of use.
     */
    @Test fun `soundness - declared identifier in all positions emits no UnknownIdentifier`() {
        runBlocking {
            checkAll(10000, arbDeclaredName) { name ->
                val source = """
                    module M {
                        func f() {
                            int $name = 0
                            $name = 1
                        }
                    }
                """.trimIndent()
                val module = parseAndAst(source)
                val result = Verifier.verifyModule(module, SymbolTable())
                val unknownIds = result.errors.filterIsInstance<VerifyError.UnknownIdentifier>()
                assertTrue(
                    "Declared identifier '$name' produced UnknownIdentifier: $unknownIds",
                    unknownIds.isEmpty()
                )
            }
        }
    }

    // ------------------------------------------------------------------ //
    // Property 2 — Completeness: undeclared identifiers always produce UnknownIdentifier
    // ------------------------------------------------------------------ //

    /**
     * **Completeness invariant**: for any program with at least one identifier reference
     * where the name does NOT appear in any scope, at least one [VerifyError.UnknownIdentifier]
     * is emitted with that exact name.
     *
     * Covers all 6 syntactic positions:
     * - 4 statement-level sites (§4.1: ASSIGNMENT_LHS, INCREMENT_TARGET, FOR_COLLECTION, LOCAL_CALL)
     * - 2 expression-context sites (OQ-11.3=(a): EXPRESSION_RHS, EXPRESSION_CONDITION via Elaboration)
     *
     * The Arb randomly picks one position per run; N=10000 exercises the full distribution.
     */
    @Test fun `completeness - undeclared identifier in any position emits UnknownIdentifier`() {
        runBlocking {
            checkAll(10000, arbUndeclaredName, arbErrorForm) { name, form ->
                val source = buildUndeclaredSource(form, name)
                val module = parseAndAst(source)
                val result = Verifier.verifyModule(module, SymbolTable())
                assertFalse(
                    "Program with undeclared '$name' in $form position should fail verification",
                    result.isSuccessful
                )
                val unknownIds = result.errors.filterIsInstance<VerifyError.UnknownIdentifier>()
                assertTrue(
                    "Expected at least 1 UnknownIdentifier for '$name' in $form position, got: ${result.errors}",
                    unknownIds.any { it.name == name }
                )
            }
        }
    }

    // ------------------------------------------------------------------ //
    // Property 3 — Shadowing soundness: inner-scope re-decl → DuplicateDeclaration
    // ------------------------------------------------------------------ //

    /**
     * **Shadowing-soundness invariant**: when a name is declared in an outer scope and
     * then re-declared in an inner scope (inside an if-branch), the error is
     * [VerifyError.DuplicateDeclaration], NOT [VerifyError.UnknownIdentifier].
     *
     * Guards against a regression where the inner re-declaration is misidentified as
     * "name not in scope" instead of "name already in scope."
     */
    @Test fun `shadowing soundness - inner-scope re-declaration is DuplicateDeclaration not UnknownIdentifier`() {
        runBlocking {
            checkAll(10000, arbDeclaredName) { name ->
                val source = """
                    module M {
                        func f() {
                            int $name = 0
                            if(1) {
                                int $name = 1
                            }
                        }
                    }
                """.trimIndent()
                val module = parseAndAst(source)
                val result = Verifier.verifyModule(module, SymbolTable())
                // Must have a DuplicateDeclaration error for the inner re-declaration
                val dupDecls = result.errors.filterIsInstance<VerifyError.DuplicateDeclaration>()
                assertTrue(
                    "Inner re-declaration of '$name' should produce DuplicateDeclaration; errors: ${result.errors}",
                    dupDecls.any { it.name == name }
                )
                // Must NOT have an UnknownIdentifier for the same name
                val unknownIds = result.errors.filterIsInstance<VerifyError.UnknownIdentifier>()
                val wrongErrors = unknownIds.filter { it.name == name }
                assertTrue(
                    "Inner re-declaration of '$name' must NOT produce UnknownIdentifier; got: $wrongErrors",
                    wrongErrors.isEmpty()
                )
            }
        }
    }
}
